### PR TITLE
ESP Easy support (sensors + relays)

### PR DESCRIPTION
**Pull request by cweiske**
Sensor values for temperature, humidity and air pressure are shown.
Supported sensors:
- "Environment - BMx280"
- "Environment - DHT11/12/22  SONOFF2301/7021"
- "Environment - DS18b20"

Relays: Current state (on/off) is shown and you can switch them
if their name ends with `~GPIO~23`.
(We do not get the GPIO number from JSON, but need it for switching)
Supported switches:
- "Switch input - Switch"

Project information:
- https://www.letscontrolit.com/
- https://github.com/letscontrolit
- https://espeasy.readthedocs.io/en/latest/

Co-author: @znbrain

An air pressure icon is missing; I used the "info" icon

# Screenshots
They were made before the units were added to the numbers.

2021-12-11 espeasy many
2021-12-11 espeasy sauna
.

### CODE REVIEW

**Comment by Domi04151309** [comment]
The list currently looks a bit messy. Is there something we can do about that?

**Comment by cweiske** [comment]
What do you mean with messy? Too long?

**Comment by Domi04151309** [comment]
It's not too long, but there doesn't seem to be any logical order. Especially with the icons, the list can feel very crowded if there is no way to recognize some sort of logical grouping or sorting.

**Comment by cweiske** [comment]
The order is determined by the setup in the ESP Easy settings. It probably seems random to you because some sensors only deliver temperature values while others have temp and humidity, and others even give 3 measured types.

Those could be displayed on one line, but that would need more work and would break the concept of "lines" that HomeApp curently has:
```
🌡 24.1°C
🌡 25.2°C   68 %    1013 mbar
🌡 35.3°C
🌡 25.0°C   50 %
```

Alternatively the order could be completely self-defined in the HomeApp settings, but that would require a complete rework.

**Comment by cweiske** [comment]
And I have to say the ESP Easy with that many sensors is pretty rare :)

**Comment by cweiske** [comment]
I've added a wiki page: https://github.com/Domi04151309/HomeApp/wiki/ESP-Easy

**Pull request merged**
